site_name: tgcf

nav:
    - Home: index.md
    - getting_started.md

repo_url: https://github.com/aahnik/tgcf

theme:
  name: readthedocs

plugins:
  - search
  - gen-files:
      scripts:
        - docs/generate.py 