blank_issues_enabled: true
contact_links:
  - name: Read Documentation
    url: https://aahnik.github.io/tgcf/
    about: Read the guides and tutorials
  - name: Ask a Question or Discuss
    url: https://github.com/aahnik/tgcf/discussions/new
    about: You may ask a question, get help about errors or start a discussion.